name: Docker build and test

on:
  push:
    branches: [ main ]

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t lab4-flask:test .

      - name: Run container
        run: docker run -d -p 5000:5000 --name flask-test lab4-flask:test

      - name: Test HTTP endpoint
        run: |
          sleep 5
          curl -v http://localhost:5000
